version: '3.7'
services:
  # hermes-queue:
  #   build: ./docker/dev
  #   container_name: taurus-queue
  #   depends_on:
  #     - taurus-redis
  #   volumes:
  #     - ./:/usr/src
  #   command: node queue.js test 1

  hermes-redis:
    container_name: hermes-redis
    image: redis:latest
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - 6379:6379